# Generated by Django 3.2.4 on 2021-06-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePostForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('body', models.TextField(verbose_name='내용')),
            ],
        ),
    ]
