# Generated by Django 3.2.4 on 2021-06-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapmo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatePostForm',
            new_name='Write_public',
        ),
    ]
