# Generated by Django 3.2.4 on 2021-06-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapmo', '0002_rename_createpostform_write_public'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Write_public',
            new_name='Public',
        ),
    ]
