# Generated by Django 3.2.4 on 2021-06-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapmo', '0004_alter_public_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='public_img/'),
        ),
    ]
