# Generated by Django 3.1.2 on 2021-06-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapmo', '0006_alter_public_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='public',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='public',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
