# Generated by Django 3.1.2 on 2021-06-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapmo', '0008_auto_20210624_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='public',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
