# Generated by Django 3.2 on 2021-06-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapmo', '0009_auto_20210624_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
