# Generated by Django 3.2 on 2021-06-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapmo', '0010_alter_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.TextField()),
                ('articleimage', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='public',
            name='img',
        ),
        migrations.AddField(
            model_name='public',
            name='img',
            field=models.ManyToManyField(blank=True, related_name='photos', to='mapmo.Photo'),
        ),
    ]
