# Generated by Django 3.2 on 2021-06-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapmo', '0011_auto_20210626_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='img',
        ),
        migrations.AddField(
            model_name='public',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='public_img/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
