# Generated by Django 3.2 on 2021-06-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapmo', '0012_auto_20210626_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.FileField(blank=True, null=True, upload_to='Friends_img/')),
                ('body', models.TextField(verbose_name='내용')),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Private',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.FileField(blank=True, null=True, upload_to='Private_img/')),
                ('body', models.TextField(verbose_name='내용')),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
            ],
        ),
    ]
